spring:
  datasource:
    url: "jdbc:mariadb://localhost:3306/manning"
    driverClassName: "org.mariadb.jdbc.Driver"
    username: "pvkr"
    password: "pvkr"
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: "create-drop"
